apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-multiwoven-server-ingress
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: api.multiwoven.com
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-multiwoven-server'
            port:
              number: 3000
        path: /
        pathType: Prefix