apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-multiwoven-postgresql
  labels:
    io.kompose.service: multiwoven-postgresql
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.multiwovenPostgresql.type }}
  selector:
    io.kompose.service: multiwoven-postgresql
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.multiwovenPostgresql.ports | toYaml | nindent 2 -}}